apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: error-handler-hpa
  namespace: owl-fenc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: error-handler-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
