apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepsearch-cache-pvc
  namespace: owl-fenc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
