apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: error-logs-pvc
  namespace: owl-fenc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
