global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "rules/alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'deepsearch_engine'
    static_configs:
      - targets: ['deepsearch-engine:3000']

  - job_name: 'unstructured_input'
    static_configs:
      - targets: ['unstructured-input:3000']

  - job_name: 'error_handler'
    static_configs:
      - targets: ['error-handler:3000']

  - job_name: 'adaptive_learning'
    static_configs:
      - targets: ['adaptive-learning:3000']
