apiVersion: v1
kind: Service
metadata:
  name: deepsearch-engine
  namespace: owl-fenc
  labels:
    app: deepsearch-engine
    service: owl-fenc
spec:
  selector:
    app: deepsearch-engine
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
