apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepsearch-engine
  namespace: owl-fenc
  labels:
    app: deepsearch-engine
    service: owl-fenc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepsearch-engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: deepsearch-engine
    spec:
      containers:
      - name: deepsearch-engine
        image: owlfenc/owl-fenc-deepsearch-engine:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: owl-fenc-secrets
              key: rabbitmq-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: owl-fenc-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: deepsearch-cache-pvc
