apiVersion: v1
kind: Service
metadata:
  name: error-handler-service
  namespace: owl-fenc
  labels:
    app: error-handler-service
    service: owl-fenc
spec:
  selector:
    app: error-handler-service
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
