apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: owl-fenc
  labels:
    app: jaeger
spec:
  ports:
  - name: query-http
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  type: ClusterIP
